//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xyanid.VisualStudioExtension.NuGetDeploy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xyanid.VisualStudioExtension.NuGetDeploy.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full.
        /// </summary>
        internal static string DebugInfoFull {
            get {
                return ResourceManager.GetString("DebugInfoFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string DebugInfoNone {
            get {
                return ResourceManager.GetString("DebugInfoNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pdbonly.
        /// </summary>
        internal static string DebugInfoPdbOnly {
            get {
                return ResourceManager.GetString("DebugInfoPdbOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dll.
        /// </summary>
        internal static string ExtensionDLL {
            get {
                return ResourceManager.GetString("ExtensionDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .pdb.
        /// </summary>
        internal static string ExtensionPDB {
            get {
                return ResourceManager.GetString("ExtensionPDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap getFormNuSpec {
            get {
                object obj = ResourceManager.GetObject("getFormNuSpec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap getFormNuSpecDisabled {
            get {
                object obj = ResourceManager.GetObject("getFormNuSpecDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap increase {
            get {
                object obj = ResourceManager.GetObject("increase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap increaseDisabled {
            get {
                object obj = ResourceManager.GetObject("increaseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0.0.0.
        /// </summary>
        internal static string InvalidVersion {
            get {
                return ResourceManager.GetString("InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;...new...&gt;.
        /// </summary>
        internal static string NewEntryIndicator {
            get {
                return ResourceManager.GetString("NewEntryIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to packages.config.
        /// </summary>
        internal static string NuGetPackageFilename {
            get {
                return ResourceManager.GetString("NuGetPackageFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .nuspec.
        /// </summary>
        internal static string NuSpecExtension {
            get {
                return ResourceManager.GetString("NuSpecExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nugetdeploy.config.
        /// </summary>
        internal static string ProjectConfigurationFilename {
            get {
                return ResourceManager.GetString("ProjectConfigurationFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullPath.
        /// </summary>
        internal static string PropertyFullpath {
            get {
                return ResourceManager.GetString("PropertyFullpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saveDisabled {
            get {
                object obj = ResourceManager.GetObject("saveDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do not use.
        /// </summary>
        internal static string UseageNone {
            get {
                return ResourceManager.GetString("UseageNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use from project.
        /// </summary>
        internal static string UseageProject {
            get {
                return ResourceManager.GetString("UseageProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use.
        /// </summary>
        internal static string UseageSetting {
            get {
                return ResourceManager.GetString("UseageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
